# Generated by Django 4.2.30 on 2026-05-25 18:36

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('code', models.CharField(default=courses.models.generate_code, editable=False, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('moderators', models.ManyToManyField(blank=True, related_name='courses_moderated', to=settings.AUTH_USER_MODEL, verbose_name='Moderadores')),
                ('students', models.ManyToManyField(blank=True, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(verbose_name='Semana')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('date', models.DateField(verbose_name='Fecha de la sesion')),
                ('video_link', models.URLField(blank=True, verbose_name='Enlace de grabacion (YouTube/Drive)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del archivo')),
                ('file', models.FileField(upload_to=courses.models.material_upload_path, verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('ppt', 'PowerPoint'), ('excel', 'Excel'), ('word', 'Word'), ('pdf', 'PDF'), ('other', 'Otro')], default='other', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.session')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='activities/instructions/', verbose_name='Archivo de instrucciones (opcional)')),
                ('due_date', models.DateTimeField(verbose_name='Fecha limite')),
                ('grade_type', models.CharField(choices=[('numeric', 'Numerica'), ('letter', 'Letra (A-F)'), ('custom', 'Personalizada')], default='numeric', max_length=10)),
                ('max_grade', models.FloatField(default=100, verbose_name='Nota maxima')),
                ('custom_grades', models.CharField(blank=True, help_text='Valores separados por coma (ej: Excelente,Bueno,Regular,Deficiente)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.session')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models.submission_upload_path, verbose_name='Archivo de entrega')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Comentario del evaluador')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.activity')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-submitted_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
