# Generated by Django 4.2.30 on 2026-05-25 18:50

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.session_video_upload_path, verbose_name='Archivo de video (MP4, max 500MB)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instruction_file',
            field=models.FileField(blank=True, null=True, upload_to='academIA/activities/instructions/', verbose_name='Archivo de instrucciones (opcional)'),
        ),
    ]
