# Generated by Django 4.2.30 on 2026-05-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_enrollment_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('source', models.CharField(choices=[('drive', 'Google Drive'), ('youtube', 'YouTube'), ('zoom', 'Zoom'), ('meet', 'Google Meet'), ('other', 'Otro enlace')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courses.session')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
