# Generated by Django 4.2.30 on 2026-05-26 00:49

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_submission_file_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=courses.models.submission_upload_path, verbose_name='Archivo de entrega'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=courses.models.submission_file_upload_path),
        ),
    ]
