# Generated by Django 4.2.30 on 2026-06-11 01:42

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_fix_file_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmaterial',
            name='file',
            field=models.FileField(max_length=500, upload_to=courses.models.material_upload_path, verbose_name='Archivo'),
        ),
    ]
